---
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
  labels:
    type: Directory
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/kubernetes/volume/homeassistant"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: homeassistant
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---                                                                                                                                         
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - image: ghcr.io/home-assistant/home-assistant:stable
        name: homeassistant
        imagePullPolicy: Always
        securityContext:
          privileged: true
        hostNetwork: true
        volumeMounts:
        - name: homeassistant-config-volume
          mountPath: /config
        resources:
          requests:
              memory: "0.5Gi"
              cpu: "0.5"
          limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
      - name: homeassistant-config-volume
        persistentVolumeClaim:
          claimName: homeassistant-config-pvc  